---
title: "ARE 212: Multiple equation estimation"
toc: false
---

<p>I served as the GSI for <a href="http://www.auffhammer.com/">Max Auffhammer</a>'s first-year PhD econometrics course, ARE 212, in Spring 2016. I built these notes off of material from <a href="https://github.com/danhammer/ARE212">Dan Hammer</a>, <a href="https://github.com/pbaylis/ARE212/">Patrick Baylis</a>, and <a href="https://github.com/kendonB/ARE212">Kenny Bell</a>. I've created some sections from scratch and expanded others, so there are likely mistakes remaining (caveat econometricus). If you find one, let me know!</p>

## syllabus

<ul>
<li><a href="../s/ARE_212_Section_Syllabus.pdf">ARE 212 Syllabus - 2016 Edition</a></li>
</ul>

## section notes

<ul>
<li>Section 1: Introduction to R [<a href="../s/are_212_section_1.pdf">PDF</a>] [<a href="../s/are_212_section_1.zip">ZIP: PDF, Rnw, &amp; data</a>]</li>
<li>Section 2: knitr and matrix operations [<a href="../s/ARE_212_Section_2.pdf">PDF</a>] [<a href="../s/Section-2.zip">ZIP</a>]</li>
<li>Section 3: Functions and looping (feat OLS) [<a href="../s/ARE_212_Section_3.pdf">PDF</a>] [<a href="../s/ARE_212_Section_3.zip">ZIP</a>]</li>
<li>Section 4: Partitioned regression and goodness of fit [<a href="../s/ARE_212_Section_4.pdf">PDF</a>] [<a href="../s/ARE_212_Section_4.zip">ZIP</a>]</li>
<li>Section 5: Hypothesis testing [<a href="../s/ARE_212_Section_5.pdf">PDF</a>] [<a href="../s/ARE_212_Section_5.zip">ZIP</a>]</li>
<li>Section 6: Figures with ggplot2 [<a href="../s/ARE_212_Section_6.pdf">PDF</a>] [<a href="../s/ARE_212_Section_6.zip">ZIP</a>]</li>
<li>Section 7: GLS and MLE [<a href="../s/ARE_212_Section_7.pdf">PDF</a>] [<a href="../s/ARE_212_Section_7.zip">ZIP</a>]</li>
<li>Section 8: Large-sample properties of OLS [<a href="../s/ARE_212_Section_8.pdf">PDF</a>] [<a href="../s/ARE_212_Section_8.zip">ZIP</a>]</li>
<li>Section 9: Non-standard standard errors I [<a href="../s/ARE_212_Section_9.pdf">PDF</a>] [<a href="../s/ARE_212_Section_9.zip">ZIP</a>]</li>
<li>Section 10: Non-standard standard errors II [<a href="../s/ARE_212_Section_10-kxr6.pdf">PDF</a>] [<a href="../s/ARE_212_Section_10-pj69.zip">ZIP</a>] [<a href="https://darinchristensen.com/post/conley-correction/">A useful note on Hsiang’s Conley SE implementation in Stata</a>]</li>
<li>Section 11: Instrumental variables [<a href="../s/ARE_212_Section_11.pdf">PDF</a>] [<a href="../s/ARE_212_Section_11-j5dr.zip">ZIP</a>]</li>
<li>Section 12: Power calculations [<a href="../s/ARE_212_Section_12.pdf">PDF</a>] [<a href="../s/ARE_212_Section_12.zip">ZIP</a>]</li>
<li>Section 13: Spatial data [<a href="../s/ARE_212_Section_13-e5pz.pdf">PDF</a>] [<a href="../s/ARE_212_Section_13.zip">ZIP</a> - largeish file]</li>
<li>Section 14: Replication [<a href="../s/ARE_212_Section_14.pdf">PDF</a>] [<a href="../s/ARE_212_Section_14.zip">ZIP</a>]</li>
</ul>
<p>Bonus: Monte Carlo primer [<a href="../s/ARE_212_monte_carlo_primer.pdf">PDF</a>] [<a href="../s/ARE_212_MC_Primer.zip">ZIP</a>]</p>

## other useful stuff

<p>Google's <a href="https://google.github.io/styleguide/Rguide.xml">R style guide</a></p>
<p>RStudio's <a href="https://www.rstudio.com/resources/cheatsheets/">cheat sheets</a> (particularly helpful: the <a href="http://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf">RStudio IDE</a> one, the <a href="http://www.rstudio.com/wp-content/uploads/2015/12/ggplot2-cheatsheet-2.0.pdf">Data Visualization</a> one, and the <a href="http://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf">Data Wrangling</a> one)</p>
<p>Swirl: <a href="http://swirlstats.com/">R tutorials</a></p>
